Repository jamf/jamfprotect, pull requests merged in 2023-11, with the labels that each got.

#97 Add new Analytic and update to existing one
  custom_analytic_detections/crash_report
  custom_analytic_detections/electron_app_code_injection
Labels: New, analytics

#98 Update README.md
  soar_playbooks/endpoint_network_isolation/README.md
Labels: documentation

#99 Task/update scripts
  jamf_protect_api/scripts/python/generate_computer_compliance_report.py
  jamf_protect_api/scripts/python/generate_computer_info_report.py
Labels: enhancement

#100 updated appid
  custom_analytic_detections/lockscreen_check
Labels: bug
